#Server port configuration
server:
  port: 8080
  
#Spring Security Configuration
spring:  security:    user:      name: sunil
      password: sunil123
      roles: ADMIN, USER
      
#Spring OAuth2 Configuration
security:  oauth2:    client:      client-id: mobile
      client-secret: pin
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token, authorization_code, password, client_credentials
      scope: READ, WRITE